<h3><?php echo $this->translate('view.slmQueue.index.index.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.slmQueue.index.index.intro'); ?>
</p>
<div class="flash-messenger">
    <?php $this->flashMessenger()->renderAll(); ?>
</div>

<?php if (count($this->queues)) : ?>
<table id="slmqueue-queue-list">
    <thead>
        <tr>
            <th>
                <?php echo $this->translate('view.slmQueue.queue.name'); ?>
            </th>
            <th>
                <?php echo $this->translate('view.slmQueue.queue.pendingCount'); ?>
            </th>
            <th>
                <?php echo $this->translate('view.slmQueue.queue.runningCount'); ?>
            </th>
            <th>
                <?php echo $this->translate('view.slmQueue.queue.buriedCount'); ?>
            </th>
            <th>
                <?php echo $this->translate('view.actions'); ?>
            </th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->queues as $queue) : ?>
        <tr>
            <td><?php echo $queue['name']; ?></td>
            <td><?php echo $queue['pending']; ?></td>
            <td><?php echo $queue['running']; ?></td>
            <td><?php echo $queue['buried']; ?></td>
            <td>
                <a href="<?php echo $this->url('slm-queue/recover', array('name' => $queue['name'])); ?>" title="<?php echo $this->translate('view.slmQueue.gotoRecover'); ?>">
                    <?php echo $this->translate('view.slmQueue.gotoRecover'); ?>
                </a>
                <br />
                <a href="<?php echo $this->url('slm-queue/list-running', array('name' => $queue['name'])); ?>" title="<?php echo $this->translate('view.slmQueue.gotoRunningList'); ?>">
                    <?php echo $this->translate('view.slmQueue.gotoRunningList'); ?>
                </a>
                <br />
                <a href="<?php echo $this->url('slm-queue/list-buried', array('name' => $queue['name'])); ?>" title="<?php echo $this->translate('view.slmQueue.gotoBuriedList'); ?>">
                    <?php echo $this->translate('view.slmQueue.gotoBuriedList'); ?>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php else : ?>
<p>
    <?php echo $this->translate('message.slmQueue.noQueuesFound'); ?>
</p>
<?php endif;