<h3><?php echo $this->translate('view.slmQueue.release.heading'); ?></h3>
<p>
    <?php echo $this->translate('view.slmQueue.release.intro'); ?>
</p>
<div class="flash-messenger">
    <?php $this->flashMessenger()->renderAll(); ?>
</div>

<p>
    <?php echo $this->translate('view.slmQueue.job.class').': '.get_class($this->job); ?><br />
    <?php echo $this->translate('view.slmQueue.queue.name').': '.$this->name; ?><br />
    <?php echo $this->translate('view.slmQueue.job.content').': '.json_encode($this->job->getContent()); ?><br />
</p>

<?php
    $this->form->setAttribute('action', $this->url('slm-queue/release', array(
        'name' => $this->name,
        'id'   => $this->id,
    )));
    echo $this->formDecorator($this->form);
?>

<a href="<?php echo $this->url('slm-queue'); ?>" title="<?php echo $this->translate('view.slmQueue.gotoOverview'); ?>">
    <?php echo $this->translate('view.slmQueue.gotoOverview'); ?>
</a>