<dl class="todo-list">
<?php
    $now = new \DateTime();
    foreach($this->todos as $todo) :
?>
    <dd <?php if (!empty($todo['deadline']) && $todo['deadline'] < $now) { echo ' class="todo-overdue"'; } ?>>
        <span class="todo-description">
            <?php echo $this->translate($todo['description']); ?>
        </span>
        <?php if (!empty($todo['deadline'])) : ?>
        <div class="todo-deadline">
            <?php echo $this->translate(array('view.todo.until', $this->dateFormat($todo['deadline'],
                \IntlDateFormatter::MEDIUM, \IntlDateFormatter::SHORT))); ?>
        </div>
        <?php endif; ?>
    </dd>
<?php endforeach;

    if (!count($this->todos)) : ?>
    <dd>
        <?php echo $this->translate('view.todo.noOpenTodos'); ?>
    </dd>
    <?php endif; ?>
</dl>